modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "kineticresistance"
version = "1.0"
displayName = "Kinetic Resistance"
authors = "zwachinabottle"
description = '''
A Minecraft mod that adds a protection enchant agaist running into walls with an elytra, anvils, falling stalactites, ect.
'''
#logoFile = ""

[[dependencies.kineticresistance]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kineticresistance]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
